/*
 * Auto-generated by lean-bindgen from simple_math.h
 * DO NOT EDIT — re-run the generator instead.
 */

#include <stdint.h>
#include "simple_math.h"

uint32_t lean_simple_math_add(uint32_t a, uint32_t b) {
    return (uint32_t)add((int)a, (int)b);
}
