/-
  Auto-generated by lean-bindgen from simple_math.h
  DO NOT EDIT — re-run the generator instead.
-/

namespace SimpleMath

@[extern "lean_simple_math_add"]
opaque add (a : UInt32) (b : UInt32) : UInt32

end SimpleMath
