"""
E2E test: run bindgen on a C header, scaffold a Lean project
around the generated files, build it with Lake, and run the binary.
"""

import subprocess
import shutil
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent


# -- The tiny Lean project we'll assemble in a temp dir ------------------

LAKEFILE = """\
import Lake
open Lake DSL

package "test" where
  version := v!"0.0.1"

lean_lib «SimpleMath» where
  srcDir := "."

@[default_target]
lean_exe "test" where
  root := `Main

extern_lib «simpleMathFfi» pkg := do
  let cDir := pkg.dir / "c"
  let buildDir := pkg.buildDir / "c"
  let simpleMathO ← buildO
    (buildDir / "simple_math.o")
    (← inputFile (cDir / "simple_math.c") false)
    #["-I", cDir.toString]
  let ffiO ← buildO
    (buildDir / "ffi.o")
    (← inputFile (cDir / "ffi.c") false)
    #["-I", cDir.toString]
  let libFile := pkg.staticLibDir / nameToStaticLib "simpleMathFfi"
  buildStaticLib libFile #[simpleMathO, ffiO]
"""

MAIN_LEAN = """\
import SimpleMath

def main : IO Unit := do
  let result := SimpleMath.add 5 3
  IO.println s!"add(5, 3) = {result}"
"""


@pytest.fixture
def lean_project(tmp_path):
    """
    Assemble a complete, buildable Lean project in a temp directory
    using files generated by bindgen.
    """
    header = REPO_ROOT / "c" / "simple_math.h"

    # 1) Run bindgen → generates SimpleMath.lean + ffi.c
    gen_dir = tmp_path / "generated"
    from bindgen.__main__ import main as bindgen_main

    ret = bindgen_main([str(header), "-o", str(gen_dir), "--module", "SimpleMath"])
    assert ret == 0, "bindgen failed"

    # 2) Place generated .lean at project root
    shutil.copy(gen_dir / "SimpleMath.lean", tmp_path / "SimpleMath.lean")

    # 3) Set up c/ with original sources + generated glue
    c_dir = tmp_path / "c"
    c_dir.mkdir()
    shutil.copy(REPO_ROOT / "c" / "simple_math.h", c_dir / "simple_math.h")
    shutil.copy(REPO_ROOT / "c" / "simple_math.c", c_dir / "simple_math.c")
    shutil.copy(gen_dir / "ffi.c", c_dir / "ffi.c")

    # 4) Write project scaffolding
    (tmp_path / "lakefile.lean").write_text(LAKEFILE)
    (tmp_path / "Main.lean").write_text(MAIN_LEAN)
    shutil.copy(REPO_ROOT / "lean-toolchain", tmp_path / "lean-toolchain")

    return tmp_path


def test_simple_math_add(lean_project):
    """Build the project and verify add(5, 3) = 8."""
    # Build
    build = subprocess.run(
        ["lake", "build"],
        capture_output=True,
        text=True,
        cwd=lean_project,
    )
    assert build.returncode == 0, f"lake build failed:\n{build.stdout}\n{build.stderr}"

    # Run
    binary = lean_project / ".lake" / "build" / "bin" / "test"
    run = subprocess.run(
        [str(binary)],
        capture_output=True,
        text=True,
    )
    assert run.returncode == 0, f"binary crashed:\n{run.stderr}"
    assert "add(5, 3) = 8" in run.stdout
