/-
  Auto-generated by lean-bindgen from opaque_ptr.h
  DO NOT EDIT — re-run the generator instead.
-/

namespace OpaquePtr

opaque MyHandleRef.Pointed : NonemptyType
def MyHandleRef : Type := MyHandleRef.Pointed.type
instance : Nonempty MyHandleRef := MyHandleRef.Pointed.property


@[extern "lean_opaque_ptr_my_handle_create"]
opaque my_handle_create (flags : UInt32) : IO MyHandleRef

@[extern "lean_opaque_ptr_my_handle_close"]
opaque my_handle_close (h : MyHandleRef) : IO UInt32

end OpaquePtr
