/-
  Auto-generated by lean-bindgen from mixed_api.h
  DO NOT EDIT — re-run the generator instead.
-/

namespace MixedApi

opaque DbConnRef.Pointed : NonemptyType
def DbConnRef : Type := DbConnRef.Pointed.type
instance : Nonempty DbConnRef := DbConnRef.Pointed.property


@[extern "lean_mixed_api_db_open"]
opaque db_open (path : String) : IO DbConnRef

@[extern "lean_mixed_api_db_close"]
opaque db_close (conn : DbConnRef) : IO UInt32

@[extern "lean_mixed_api_db_error"]
opaque db_error (conn : DbConnRef) : IO String

@[extern "lean_mixed_api_db_execute"]
opaque db_execute (conn : DbConnRef) (sql : String) : IO UInt32

end MixedApi
