/*
 * Auto-generated by lean-bindgen from string_api.h
 * DO NOT EDIT — re-run the generator instead.
 */

#include <stdint.h>
#include <lean/lean.h>
#include "string_api.h"

lean_object* lean_string_api_get_greeting(uint32_t id, lean_object* w) {
    const char * result = get_greeting((int)id);
    lean_dec(w);
    return lean_io_result_mk_ok(lean_mk_string(result));
}

lean_object* lean_string_api_set_name(lean_object* name, lean_object* w) {
    const char *c_name = lean_string_cstr(name);
    uint32_t result = (uint32_t)set_name(c_name);
    lean_dec(name);
    lean_dec(w);
    return lean_io_result_mk_ok(lean_box((size_t)result));
}
