/-
  Auto-generated by lean-bindgen from string_api.h
  DO NOT EDIT — re-run the generator instead.
-/

namespace StringApi

@[extern "lean_string_api_get_greeting"]
opaque get_greeting (id : UInt32) : IO String

@[extern "lean_string_api_set_name"]
opaque set_name (name : String) : IO UInt32

end StringApi
